apiVersion: v1
kind: Service
metadata:
  # Define in repository config in gitlab
  name: ${PROJECT_NAME}-service
  # Define in repository config in gitlab
  namespace: ${PROJECT_NAMESPACE}
  labels:
    app: ${PROJECT_NAME}-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: low
      protocol: TCP
      targetPort: 80
  selector:
    app: ${PROJECT_NAME}
